# Generated by Django 4.2.5 on 2023-09-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название блюда')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category', verbose_name='Категория')),
            ],
        ),
    ]
