# Generated by Django 4.2.5 on 2023-09-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredients_alter_recipes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='Рецепты', to='recipes.ingredients', verbose_name='Ингредиенты'),
        ),
    ]
