# Generated by Django 4.2.5 on 2023-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredients_title_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes', verbose_name='Изображение блюда'),
        ),
    ]
