# Generated by Django 4.2.5 on 2023-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscription',
            field=models.BooleanField(verbose_name='Активна ли подписка'),
        ),
    ]
