# Generated by Django 4.2.5 on 2023-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_choice',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Выбор Плана'),
        ),
    ]
