# Generated by Django 4.2.5 on 2023-09-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_subscriptionplan_plan_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='current_subscription_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user', to='recipes.subscriptionplan', verbose_name='Текущий План Подписки'),
        ),
    ]
