# Generated by Django 4.2.5 on 2023-09-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_user_category_user_current_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='end_subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_subscription',
        ),
        migrations.AlterField(
            model_name='user',
            name='current_subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='recipes.subscriptionplan', verbose_name='Текущий план подписки'),
        ),
    ]
